user model vol.1
norbx/gms_api pull request #1
Opened 2020-09-27 17:04 UTC by AniaKujawa

2020-11-11 23:02 UTC, norbx approved these changes

2020-11-11 23:03 UTC, norbx requested changes

2020-11-11 23:03 UTC, norbx commented on gms_api/settings.py
> -SECRET_KEY = 'kp5rd&j^-(ewqs7hsuf=!clgqaef99=_e@-h#dqty$p#3)8y7&'
Trzeba zrobić coś z tym kluczem, GitGuardian nie przepuści Ci pr inaczej

2020-11-11 23:05 UTC, norbx commented
Tytuł PRa też nie jest najbardziej deskryptywny :D może `Add user model`, coby się trzymać konwencji?

2020-12-13 18:12 UTC, AniaKujawa commented on gms_api/settings.py
> +import environ
dobra, to następnym razem 👍

2020-12-13 18:14 UTC, AniaKujawa commented on gms_api/settings.py
> -SECRET_KEY = 'kp5rd&j^-(ewqs7hsuf=!clgqaef99=_e@-h#dqty$p#3)8y7&'
ej, ale przecież to jest usunięte właśnie, a dodane jest pobieranie kluczu z enva 🤔

2020-12-14 12:49 UTC, norbx commented on gms_api/settings.py
> -SECRET_KEY = 'kp5rd&j^-(ewqs7hsuf=!clgqaef99=_e@-h#dqty$p#3)8y7&'
hmhm, rzeczywiście, w takim razie to ja to przeoczyłem przy init pushu. jeśli nie uda ci się nic z tym zrobić, to spróbuj to pusznąć z forcem

2020-12-15 18:51 UTC, merged